apiVersion: v1
kind: ConfigMap
metadata:
  name: assistant-proxy
data:
  LLAMA_STACK_URL: http://llamastack.llamastack.svc.cluster.local:8321
  ARGO_CD_URL: https://argocd-server-demo-gitops.apps.home.ocplab.com
  LOGGING_LEVEL: DEBUG
  INSECURE_SKIP_VERIFY: "true"
